### ISSUE TITLE
Any more fishing locations coming?

### ISSUE THREAD

**Issue by ChikyuTenshi** [kpreisser/MouseClickSimulator#10]
Hey, So I love your tool so much, Saved me the headache of fishing

But I was wondering if any more areas are gonna be supported sometime soon? I myself would try and update it with more but I don't know how the code works, If you could explain it to me I might be able to do it myself

Cheers

**Comment by kpreisser** [comment]
Hi,
thanks for logging the issue!

I didn't yet plan for adding other fishing locations, but maybe if I find some time, I can look into adding some (e.g. Alto Avenue as requested in #12).

As for the meaning of the `<AutomaticFishing>` element attributes: Please see https://github.com/kpreisser/MouseClickSimulator/issues/8#issuecomment-215971103 where they are explained.
However I probably should add a page to the Wiki where this is also described.
Thanks

**Comment by thezoid** [comment]
The estate? A big one in terms of species collection

**Comment by kpreisser** [comment]
Hi,
I remember from the original TT that it was possible to sell the fish on the fishing pond at the estate during the "Bingo" activity. I don't know if this is still possible in TTR, but if yes, it would be possible to automate fishing at least during that time. Otherwise it would be a bit hard to find a way to seel the fish.

**Comment by thezoid** [comment]
do you think it could be helpful even if it didn't auto-sell?

**Comment by kpreisser** [comment]
Hi,
yes, i think it could be helpful. I will see if I can put together a XML file for fishing at the estate.

**Comment by RainyKitsune** [comment]
Any updates on the Estate XML? I tried to make it myself, but I can't figure out how to make my toon not fish the water instead of the dark spots.

**Comment by kpreisser** [comment]
Hi,

I prepared an XML to fish at the estate, but noticed that the view angle at this location seems to be different to the other locations, so the simulator couldn't correctly cast the rod.
Unfortunately, I did not yet have time to investigate this further.

**Comment by slayer1555** [comment]
So how would we go about making it work. I know you dont have the time but what could i change to make it work. Would it be the area it scans or something?

**Comment by kpreisser** [comment]
Hi there,

Estate fishing has finally been implemented with #56, which includes auto-selling the fish (as it seems TT Rewritten added a place to sell the fish in the meantime).

Thanks!
