### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by obileg** [kpreisser/MouseClickSimulator#11]
Every time i try to run the application, my computer just freezes up. Ive ran the build, and ive left it on overnight, so i know its not just loading. If you could please help me it would be great. I am currently using windows 10, if that helps.

**Comment by kpreisser** [comment]
Hi,

do you mean that when you run the "BUILD.cmd" file, it hangs (it does not show "Build successful")? Or does the build complete, and when you try to start the built "TTMouseclickSimulator.exe", nothing happens?
Thanks!

**Comment by kpreisser** [comment]
I'm closing the issue for now. If it still occurs, please reopen it. Thanks!
