### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by HypnoPants** [kpreisser/MouseClickSimulator#13]
Everytime I try to build it, I get this error...

Building the TTR Mouse Click Simulator...

ERROR: MSBuild not found at "F:\SparePrograms\MSBuild\14.0\Bin\MSBuild.exe"!
Press any key to continue . . .

Not  sure what to do

**Comment by kpreisser** [comment]
Hi,
did you follow the instructions in the wiki to install  <a href="https://go.microsoft.com/fwlink/?LinkId=615458" target="_blank">Microsoft Build Tools 2015</a>?
Which Windows-Version are you using?

Can you look if the folder `C:\Program Files (x86)\MSBuild` (or for 32-bit, `C:\Program Files\MSBuild`) exists, and alternatively `F:\SparePrograms\MSBuild`?
Thanks!

**Comment by kpreisser** [comment]
I'm closing the issue for now. If it still occurs, please reopen it. Thanks!

**Comment by HypnoPants** [comment]
I'm so sorry, I thought I had replied already!

I did manage to get it working, it seems one of the .net setups I installed was corrupt, though it said it installed correctly it was missing a file or two. When I got a fresh install of the .net files everything worked fine :)
