### ISSUE TITLE
Toontown Operation Dessert Storm Support?

### ISSUE THREAD

**Issue by 0x526f6d656f** [kpreisser/MouseClickSimulator#16]
Schön zu sehen, dass du noch Tools machst für TT^^

Könntest du eventuell Support for ODS machen? www.opdessertstorm.com
Bei denen muss man rechtsklicken um den Fisch einzufangen.

**Comment by zxstai** [comment]
This would be nice.

**Comment by kpreisser** [comment]
Hi,
I will look into this when I have some time.
Thanks!
