### ISSUE TITLE
Problem in Walrus Way, Tenor Terrence

### ISSUE THREAD

**Issue by Volxahl** [kpreisser/MouseClickSimulator#17]
Hi,

In Walrus Way right after selling the fish, the toon will run towards the dock and run through hitting the wall, interrupting the simulation. Can you find a fix to this? Also, in Tenor Terrence the aim towards the fish in the pond isn't working and it lands on a spot on the pond that isn't the fish. Thank you for reading

**Comment by kpreisser** [comment]
Hi,
I improved the scan area so the fishing in Tenor Terrace should work now.
However, I cannot reproduce the issue in Walrus Way; the toon does not run through for me. Can you try again to see if the problem still occurs?
Thanks!

**Comment by stephanie121** [comment]
It still occurs. The toon runs at an angle, to the right of the fisherman. Sometimes the toon turns enough and sometimes the toon doesn't turn enough.

**Comment by kpreisser** [comment]
Hi,
I updated the key press durations in the recent commits, which should work better now.
Thanks!
