### ISSUE TITLE
Bot Interrupted?

### ISSUE THREAD

**Issue by mitchbro** [kpreisser/MouseClickSimulator#19]
When i build and run the bot, it loads fine. But after i select start in walrus way, the bot spits back "Bot interrupted" in a dialog box

**Comment by kpreisser** [comment]
Hi,

when the "Bot interrupted" message appears, what exactly does it say?

**Comment by kpreisser** [comment]
WIth the new background mode, this should no longer occur as the window does no longer need to stay active/in the foreground.
