### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Ross123123** [kpreisser/MouseClickSimulator#21]
When I try to run the script to build it, the command prompt spits this out:

C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1098,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in
place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [C:\Users\rossl\Desktop\MouseClickSimulatormaster\TTMouseclickSimulator\TTMouseclickSimulator.csproj]

**Comment by kpreisser** [comment]
Hi,

did you download and run the <a href="https://go.microsoft.com/fwlink/?LinkId=528261" target="_blank">.NET Framework 4.6 Targeting Pack</a> as described in the [Wiki page](https://github.com/kpreisser/MouseClickSimulator/wiki/Running-the-Simulator)?
