### ISSUE TITLE
Playground Locations

### ISSUE THREAD

**Issue by stephanie121** [kpreisser/MouseClickSimulator#22]
While playground locations have higher risk, some fish absolutely require fishing in a playground, namely Daisy Gardens or Donald's Dock (and player piano tuna in Minnie's Melodyland). These fish are:
-bull dog fish
-dalmatian dog
-Clydesdale sea horse
-Arabian sea horse
-kiddie pool shark
-swimming pool shark
-Olympic pool shark
-Captain Cutthroat Trout
-upright piano tuna
-player piano tuna
An alternative and possibly more appealing location is the Estate. Only these fish can be caught there (and not a street):
-bull dog fish
-Clydesdale sea horse
-Arabian sea horse
It's still a huge risk, though I think the option for those three playgrounds should be there. However, I haven't attempted to catch them, so I wouldn't know how long it takes. All ultra rares are covered, and I think that was the main purpose. Thank you regardless for all of the other fishing locations. :)

**Comment by Derooms** [comment]
I can make those for you but I'd highly advise against it... None of those fish are ultra rare so even though streets aren't the best place to find them, if you just go look for an ultre rare those will eventually show up... Plus I'd rather be safe than sorry, it's not like it will matter too much if mouse click takes an hour longer to catch those, you wouldn't be wasting your time anyway

**Comment by stephanie121** [comment]
No worries :)
Thank you for considering it.
