### ISSUE TITLE
Estate Pond?

### ISSUE THREAD

**Issue by BlackAnthem849** [kpreisser/MouseClickSimulator#29]
Can a bot for the estate pond be implemented as well? Thanks!

**Comment by PiriNoodle** [comment]
Did you ever get around to making one for the estate?

**Comment by BlackAnthem849** [comment]
I don't think it's happened yet :\ But the only reason we'd need the estate is for All Star Fish, but I got it once in the Brrrgh, and once in Donalds Dock. So it might come when hunting the others. If it helps any, I got the All Star Fish on my third bucket in Lighthouse Lane with a Gold rod, heh.

**Comment by PiriNoodle** [comment]
Do you get the problem with walrus way?


Sent from Yahoo Mail for iPhone


On Wednesday, January 17, 2018, 04:33, BlackAnthem849 <notifications@github.com> wrote:


I don't think it's happened yet :\ But the only reason we'd need the estate is for All Star Fish, but I got it once in the Brrrgh, and once in Donalds Dock. So it might come when hunting the others. If it helps any, I got the All Star Fish on my third bucket in Lighthouse Lane with a Gold rod, heh.

**Comment by kpreisser** [comment]
Thanks for creating this issue! This has been fixed which #56, which added an estate fishing project for Toontown Rewritten (`Auto Fishing - Estate.xml`).
