### ISSUE TITLE
Walrus Way Issue

### ISSUE THREAD

**Issue by PiriNoodle** [kpreisser/MouseClickSimulator#30]
For some reason, I come back to my computer to find my toon always logged off for being sleepy and going to bed. Ive managed to catch the issue. It seems to sell the fish, and then run over the dock and into the fence and it just stays there. I havent altered the code for the pre-set walrus way, so why is this happening? Its very frustrating because its intermittent and doesnt happen every time but eventually it does happen.

Also can you give me an XML file for the brghh playground and also my estate? Also alto avenue?

**Comment by PiriNoodle** [comment]
Can someone sort this damn Walrus Way file out please! This is getting pathetic! It over-runs the dock after selling the fish and stands next to a wall until it falls asleep and logs out. If it doesn't over-run the dock, then it runs past it by running too far to the left.

Only sometimes it will run on to the dock after selling the fish, but not a lot! I need this Walrus Way file adjusted, I cannot use it!

**Comment by WeeajEw** [comment]
i am having the same issue, but i dont think it will be fixed because this has not been commited since june 4th

**Comment by P-Medicado** [comment]
For Walrus Way, the return to dock action is in its xml file here is a portion of it. Maybe you can fine toon the settings to work better. Please let me know bc I want to work on a lot of the issues open in this repo.

`<Compound type="Sequential" loop="false" maximumPause="300" minimumPause="50">
<PressKey duration="720" key="Up"/>
<PressKey duration="1020" key="Left"/>
<PressKey duration="1900" key="Up"/>
<Pause duration="1000"/>
<SellFish/>
<Pause duration="1000"/>
<PressKey duration="2118" key="Down"/>
<PressKey duration="800" key="Left"/>
<PressKey duration="1800" key="Up"/>
<Pause duration="2200"/>
</Compound>`

**Comment by PiriNoodle** [comment]
Im confused. What is that you gave me? Is this the fixed script?

**Comment by P-Medicado** [comment]
@PiriNoodle unfortunately it isn't the working script. It is the part of the script that handles getting back to the platform and is not very accurate. Right now I'm working on a Racer for TTR so I haven't been testing changing to the Walrus Way script. 

After it says `<SellFish/>` it stops then presses the down arrow key (`<Pause duration="1000"/> <PressKey duration="2118" key="Down"/>`)

It makes your toon turn left (`<PressKey duration="800" key="Left"/>`) 

Finally run forward trying to get to the dock (`<PressKey duration="1800" key="Up"/>`)

**These numbers (in quotes after the word duration) are wrong. If you can change them - they are in 1,000ths of a second - you will be able to reach the dock always!**

**Comment by kpreisser** [comment]
Hi, sorry for the late reply.

In the recent updates I tweaked the key press durations for Walrus Way a bit, so it should work better now with the current game version.

Thanks!
