### ISSUE TITLE
"Simulator interrupted"

### ISSUE THREAD

**Issue by 1ay** [kpreisser/MouseClickSimulator#31]
When I leave this on, in the middle of the first 1 or 2 buckets, it casts in the middle at nothing and stops working, then the simulator says this message:

![problem](https://user-images.githubusercontent.com/40993497/42441923-90504104-8326-11e8-9a26-f35ce8c07ea7.PNG)

I really don't know what to do?

**Comment by kpreisser** [comment]
This should no longer be an issue with the new background mode, where the window no longer needs to stay active/in the foreground.
