### ISSUE TITLE
TTCC Support?

### ISSUE THREAD

**Issue by KensonPlays** [kpreisser/MouseClickSimulator#32]
Would it be possible for it to work with the TTCC server? `CorporateClash.exe`

**Comment by simplyargyll** [comment]
Id like for this to be supported as well

**Comment by danylopez123** [comment]
I was just about to ask that.

**Comment by atemerino** [comment]
You can easily port this yourself, just change the executable string to CC's and it should work fine. You might have to alter some RGB values in the xml files, but that's all very simple.

https://github.com/kpreisser/MouseClickSimulator/blob/67c4a87c1db7fd906f3dfc88aa6cc26c51dc6d4f/TTMouseclickSimulator/Core/ToontownRewritten/Environment/TTRWindowsEnvironment.cs#L14

**Comment by kpreisser** [comment]
Hi, sorry for the delay. I added support for Corporate Clash in the current version.
