### ISSUE TITLE
Fishing 🎣 

### ISSUE THREAD

**Issue by selenaxbeanie** [kpreisser/MouseClickSimulator#36]
So I have it built and so forth and I go to walrus way. It will start to fish, but it will not cast the fishing pole almost like nothing is being detected. Is there something wrong with the sample file or is this on my end?

**Comment by selenaxbeanie** [comment]
It isn’t detecting fish on any street

**Comment by kpreisser** [comment]
Hi, sorry for the late reply.

I just added a bunch of new project files (the ones with `Winter Theme` in their name), which should work again in the current game version.

Thanks!
