### ISSUE TITLE
Tenor Terrace Fishing Not Working

### ISSUE THREAD

**Issue by BeteNoire1** [kpreisser/MouseClickSimulator#38]
Hello, good afternoon.

Happy Hump Day! :)

I hope that someone can support with this, every time I attempt to fish in Minnie's Melodyland -Tenor Terrace my casts are going far out to the back right side and never going to a bubble. It is almost as if the trigger to search for a bubble is not functioning and it casts in the same spot everytime.
![MML Tenor Terrace Cast Example](https://user-images.githubusercontent.com/97632380/149213330-3fc15b18-8a3e-43a0-b5f8-d39c69370150.png)

**Comment by kpreisser** [comment]
Hi, this could happen if you are standing on the wrong fishing board. For Tenor Terrace, you should stand on the rear right board (see below arrow):
![grafik](https://user-images.githubusercontent.com/13289184/150608519-db79322d-7807-4ee9-a9e3-b5fa3bab7ba1.png)

Thanks!
