### ISSUE TITLE
Fishing Stops

### ISSUE THREAD

**Issue by masonl14** [kpreisser/MouseClickSimulator#40]
Hi

First of all thank you for your work. I've used this extensively for years now and it has saved me a lot of boredom. Truly thank you.

I've returned to TTR after a break and got the update for the engine name change. The gardening worked great, however, the fishing, for some reason, just stops. Oddly enough it stops after catching somewhere between 10-20 fish. I wonder if it's just stopping after 20 casts? Anyway, I tried it in 3 locations, multiple times, and it always happens. 

It fishes perfectly like before, but then stops, doesn't start again, and my toon falls asleep and logs out. Also, when I get back to my PC, I have to click 'stop' on the interface in order to regain control of the game.

**Comment by kpreisser** [comment]
Hi @masonl14,
thanks for logging this issue.

I assume you are using background mode in the simulator (which is now enabled by default). I'm not sure why it would suddenly stop fishing, it seems the mouse messages sent to the window don't work any longer. From my previous experience, this could happen when you move the mouse pointer over the Toontown window while the simulator is active.

Does it work when you uncheck "Enable background mode" before clicking on Start? (I hink I will have to disable background mode by deafult, as it apparently doesn't always correctly.)

Thanks!

**Comment by kpreisser** [comment]
Background mode is now disabled by default (like it was in earlier versions that didn't support this mode).

**Comment by masonl14** [comment]
Thanks for getting back so quick.

Just tried twice on Elm St with background mode disabled and the issue persists. One thing I did notice that I didn't before is that the last cast is not 'aimed' if you will at the fish bubbles. It just quickly casts one straight forward without aiming.

Could this possibly just be an issue on my end?

**Comment by kpreisser** [comment]
Hi,

yes, the last cast is always to fixed position, to ensure the toon is not rotated when moving it to the fisherman later. For this last cast, the simulator waits a bit longer (until the fishing timer goes down to 19 seconds) for the fish result dialog to occur, and should then click on the Quit Fishing button. You can see this in the two videos linked in the README.md file.
Does the simulator not click on the quit fishing button in your case before the timer goes to 0? Can you check which action is highlighted in blue in the simulator during that time?
Thanks!

**Comment by masonl14** [comment]
I'm sorry for wasting your time.. it was because I was using WASD..

I think I changed it on the last one I had downloaded, but I forgot how. Do I just change the sample projects and make them read only?

**Comment by masonl14** [comment]
I'm sorry for wasting your time.. it was because I was using WASD..

I think I changed it on the last one I had downloaded, but I forgot how. Do I just change the sample projects and make them read only?

**Comment by masonl14** [comment]
Oops didnt mean to do that

**Comment by kpreisser** [comment]
Hi,

> I'm sorry for wasting your time.. it was because I was using WASD..

No problem. I previously didn't consider this case (as older TT Rewritten versions didn't have the option to change controls), but ideally the simulator should have direct support for using WASD keys as I think other people may also use WASD instead of arrow keys.

I have now added an option **"Use WASD instead of array keys for movement"** to the simulator which, when enabled, automatically converts arrow keys (specified in the project file) to WASD keys, so you don't need to manually edit the project files.

Thank you!
