### ISSUE TITLE
BUILD.cmd Error

### ISSUE THREAD

**Issue by Heimerdinger121** [kpreisser/MouseClickSimulator#50]
"Building the TTR Mouse Click Simulator...

'"dotnet.exe"' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . ."

This is the following message I get on my cmd.exe window when I try to build the code. Don't know exactly what's wrong here.

**Comment by kpreisser** [comment]
Hi,

it seems you are missing the .NET SDK. Please follow the steps from the wiki page [Running the Similator](https://github.com/kpreisser/MouseClickSimulator/wiki/Running-the-Simulator), which contains a link to download the current .NET SDK (6.0 or 7.0).

Thanks!
