### ISSUE TITLE
Is Doodle Interaction Panel one of the actions built-in?

### ISSUE THREAD

**Issue by JJBrasch** [kpreisser/MouseClickSimulator#57]
Is Doodle Interaction Panel one of the actions built-in? You said in the Development section on the code overview that:

"Currently, the implementation contains actions for pressing keys, writing text, SpeedChat, Doodle Interaction Panel and the Automatic Fishing Function. Furthermore, an action for planting a flower is supported."

If the Doodle Interaction Panel is an action like SpeedChat is, how is the action utilized?

Ex. here is some code I tried using but it fails to register that "Doodle Interaction Panel" is a valid action

'
<?xml version="1.0" encoding="utf-8"?>
<SimulatorProject xmlns="https://github.com/TTExtensions/MouseClickSimulator">
    <Title>Dance Twice Then Scratch</Title>
    <Description>This project instructs the pet to 'Dance' twice and then performs a 'Scratch' through the Doodle Interaction Panel.</Description>

    <MainAction>
        <Compound type="Sequential" loop="true">
            
            <Loop count="2">
                <Compound type="Sequential" loop="false">
                    <Speedchat menuItems="3, 0, 2" /> 
                    <Pause duration="1000" /> 
                </Compound>
            </Loop>

            
            <DoodleInteractionPanel menuItems="Scratch" />
            <Pause duration="1000" /> 
        </Compound>
    </MainAction>
</SimulatorProject>
'
Anything that should be changed to make this a valid xml?

**Comment by kpreisser** [comment]
Hi! Yes, the doodle panel should work. You can use one of the following:
```xml
<DoodlePanel button="Feed" />
<DoodlePanel button="Scratch" />
<DoodlePanel button="Call" />
```

(The names of the available actions are listed in the [`XmlProjectDeserializer`](https://github.com/kpreisser/MouseClickSimulator/blob/main/TTMouseclickSimulator/Project/XmlProjectDeserializer.cs) class.)

Thanks!

**Comment by JJBrasch** [comment]
Awesome!!!! Thank you @kpreisser
