### ISSUE TITLE
File type

### ISSUE THREAD

**Issue by Subzero2474** [kpreisser/MouseClickSimulator#6]
Hello i feel like a massive idiot, i changed some of the file types to open with a different program and now i cant change them back, the previous restoration doesn't work because i've deleted the file several times and re downloaded it and it stays the same file :| really really stuck please help

**Comment by Subzero2474** [comment]
The file i changed was TTmouseclickSimulatior and i changed it to a adobe acrobat document (i miss clicked FYI)

**Comment by Subzero2474** [comment]
Okay Ignore all that i sorta fixed it, i uninstalled acrobat and it changed back to the original file type but whe i try and open the simulator it doesn't work

**Comment by TTExtensions** [comment]
Hi,
can you give more details about what exactly doesn't work? Were you able to build the simulator with the BUILD.cmd file as described in the [wiki page](https://github.com/TTExtensions/MouseClickSimulator/wiki/Running-the-Simulator)?
Thanks!

**Comment by Subzero2474** [comment]
Hi I built it and went through the bin file ect and then I clicked on the simulator and it just freezes and eventually closes no idea what to do, thanks


Sent from Outlook Mobile






On Wed, Jan 27, 2016 at 11:03 AM -0800, "TTExtensions" <notifications@github.com> wrote:





Hi,
can you give more details about what exactly doesn't work? Were you able to build the simulator with the BUILD.cmd file as described in the [wiki page](https://github.com/TTExtensions/MouseClickSimulator/wiki/Running-the-Simulator)?
Thanks!

---

**Comment by TTExtensions** [comment]
Hi,
if you still have this problem, can you open event log (press the Windows button, then enter `eventvwr`), then navigate to "Windows Logs", then "Application", and check if there is some error entry with ".NET Runtime"? If yes, can you share the text that is displayed when clicking on that entry, this might show the reason for the simulator to close.
Thanks

**Comment by kpreisser** [comment]
Please reopen if the problem still exists. Thanks!
