### ISSUE TITLE
Fishing Not Working

### ISSUE THREAD

**Issue by TPCo0Lz** [kpreisser/MouseClickSimulator#9]
Every time I go to fish, A pop-up window appears ( after I click start) Saying: Access is denied. Please Help!!

**Comment by kpreisser** [comment]
Hi,
which Windows version (7, 8, 10) are you using?

To get more information where the error is happening, can you please do the following:

1. Download [this ZIP file](https://github.com/kpreisser/MouseClickSimulator/archive/VerboseErrors.zip) and extract it. This file contains a modified version of the simulator that should print more verbose error messages.
1. In the extracted folder, run the `BUILD` script, then start the Mouse Click Simulator (`TTMouseclickSimulator.exe` in the `bin\Release` folder).
1. Open the fishing project (just like you did before) when TTR is running, and click on Start.
1. The Mouse Click Simulator should now display a verbose error message. Please take a screenshot of it, save it to a file and attach it to the bug report (by dragging & dropping it into the bug report textbox).

Thanks!

**Comment by stephanie121** [comment]
![capture1](https://cloud.githubusercontent.com/assets/28494833/25777049/6e3151c6-3296-11e7-8df3-ed4dce2c74ed.JPG)

**Comment by stephanie121** [comment]
I'm using windows 10 and I have this issue, though the text just says "Access is denied"

**Comment by kpreisser** [comment]
Hi,
one possibility where this message would occur was when the process (`TTREngine.exe`) has also been started by another user.
Can you try with the current version of the Mouse Click Simulator, if this issue still occurs? Thanks!

**Comment by stephanie121** [comment]
For me, the issue was fixed. Thank you.

**Comment by kpreisser** [comment]
Thanks! I'm closing the issue.
